- name: Test connectivity
  hosts: all
  vars:
    file: ~/file.txt
  tasks:
    - name: ping remote host
      ping:
    - name: get date
      command: date
    - name: Check that the somefile.conf exists
      stat:
        path: '{{ file }}'
      register: stat_result

    - name: Create the file, if it doesnt exist already
      file:
        path: '{{ file }}'
        state: touch
      when: not stat_result.stat.exists

    - name: create file if it does not exist
      lineinfile:
        path: '{{ file }}'
        line: "this is my hello message"
      register: out

    - name: print output
      debug:
        msg: "line already exists? {{ out }}"
